// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kifeiibiobebasbkgeds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZmVpaWJpb2JlYmFzYmtnZWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzcxMjYsImV4cCI6MjA3MDY1MzEyNn0.tERxgtIkPJcbc64FFs1oJXiSKGidrrxTNZQ6yWmxCjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});